language: ruby
cache: bundler
script: bash build.sh
branches:
  only:
  - master
rvm:
- 2.3.0
env:
  global:
  - secure: lgLc9Vv0N63tCSXhrHfRO7Oy8P7byZjdmWo+hvsaM9+UVRVLQGkSSCeS9+/t7DH0F6VFw+gz3ipx3p8M0FsIgXCdfA3SrKwRQ/XiEi5WfrdnLc9DUOkKCAHHRX+aDIK4A4XVDec4AOcaVAS7qSWzSoX//D+NQkIKsO2qaxQqUhx4V7eYyJYstGStJhnk+jp0Ym+X5PXmZwfUhEcbDLPZ41QmiQqEj9xDTumvxPZ2s2O5WKB/tETCeeLP8UM4LmuvmlUqrL0WUs8kj4kK4BTBqQK+VZ17bJoXm3GEFCN6wT7cF2uoHxYwSjvyB2rPipdiuk/Z0s4whP91SONB1+Y/cYHY2GSZZqVhM9zo/Z8rkg+S0rfgFY2uSeUENqzVAHuYUktkoWkNjnNRLYSjUThhtkfWPG9VyhB7T8BzUCFb8YNwsrT8OhsvvDZIKnTCtQcGMMAiVhRnjKlkPdbATtaa24NY4HowWBAM5tCmfsXR/S9zhXFOuklCtzGxsE+vtMqPYNvdPjPFOY3lIodZAx1q9Ps/j+xKOb17FTW69AMG6Nx3rzMzy5j2cOeOFbqTto5XkeL6NG1DPdk9W1ylMyLLYiVxuIcQpjphSMql3SEEDI2pMdLoUNqV8RTfzOWsEiiPsIWkOUCDlN2buF2anjQNB8EEn2gbYUZ85JX9LrJF4yg=
